version: "3"

services:

  ubuntu:

    image: ubuntu:latest
    container_name: ubuntu
    restart: always

    environment:

      COMPOSE_PROJECT_NAME: ubuntu

    volumes:
      - ./data:/mnt/data

    ports:
      - "222:22"

    network_mode: bridge
